import crypto from "node:crypto";
import PlanCache from "../models/PlanCache.js";

/**
 * Fingerprinted cache for validated AI plans (P1 cost/latency optimization).
 * Same profile + same summary + same model = same cache key, so repeat
 * generations skip the billed Gemini call entirely.
 */

/**
 * Deterministic serialization: recursively sorted keys, so semantically
 * identical inputs hash identically regardless of key order.
 * @param {unknown} value Any JSON-compatible value.
 * @returns {string} Canonical string.
 */
export function stableStringify(value) {
  if (Array.isArray(value)) {
    return `[${value.map(stableStringify).join(",")}]`;
  }
  if (value && typeof value === "object") {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value) ?? "null";
}

/**
 * Derives the cache key for a generation request. The model name is part of
 * the key so a model upgrade never serves plans generated by another model.
 * @param {{ userProfile?: unknown, nutritionSummary?: unknown, model?: unknown }} input Request inputs.
 * @returns {string} Hex SHA-256 fingerprint.
 */
export function hashPlanRequest(input) {
  const canonical = stableStringify({
    userProfile: input?.userProfile ?? null,
    nutritionSummary: input?.nutritionSummary ?? null,
    model: input?.model ?? null,
  });
  return crypto.createHash("sha256").update(canonical, "utf8").digest("hex");
}

/**
 * Looks up a cached validated plan. Never throws — cache failures must not
 * break generation (fail-open to a fresh provider call).
 * @param {string} key Fingerprint from hashPlanRequest.
 * @returns {Promise<any|null>} Cached plan data or null.
 */
export async function getCachedPlan(key) {
  try {
    const entry = await PlanCache.findOne({ key }).lean();
    return entry?.payload ?? null;
  } catch (err) {
    console.error("Plan cache lookup failed:", err?.message ?? err);
    return null;
  }
}

/**
 * Stores a validated plan under its fingerprint. Never throws — a failed
 * write must not fail an otherwise successful generation.
 * @param {string} key Fingerprint from hashPlanRequest.
 * @param {any} payload Validated plan data.
 * @returns {Promise<void>}
 */
export async function setCachedPlan(key, payload) {
  try {
    await PlanCache.findOneAndUpdate({ key }, { key, payload }, { upsert: true });
  } catch (err) {
    console.error("Plan cache write failed:", err?.message ?? err);
  }
}
